use sakila;

-- Retrieve the total number of rentals made in the Sakila database. 
select count(*) from rental;

-- Find the average rental duration (in days) of movies rented from the Sakila database.
select ceiling((avg(rental_duration))) from film; 

-- Display the first name and last name of customers in uppercase.
select upper(first_name) as 'first name' , upper (last_name) as 'last name' from customer; 

-- Extract the month from the rental date and display it alongside the rental ID. 
select rental_id,  month(rental_date) from rental;

-- Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select count(*) ,customer_id from rental group by customer_id;

-- Find the total revenue generated by each store.
select store_id,sum(am.total_amount) as revenue from staff st inner join
 (select sum(amount)  total_amount,staff_id from payment group by staff_id) as am 
 on am.staff_id=st.staff_id group by store_id;
 
 -- Display the title of the movie, customer s first name, and last name who rented it.
 select c.first_name,c.last_name, f.title from rental r 
 inner join customer c on r.customer_id=c.customer_id
 inner join inventory i on r.inventory_id=i.inventory_id
 inner join film f on i.film_id=f.film_id;
 
 -- Retrieve the names of all actors who have appeared in the film "Gone with the Wind." 
 select distinct (f.title) ,a.first_name,a.last_name
 from film f inner join 
 film_actor fc on f.film_id=f.film_id
 inner join actor a on a. actor_id=fc.actor_id
 where f.title='Gone with the Wind';
 
 
 select first_name,last_name,'Gone_with the wind' as title from actor where actor_id in(
select actor_id from film_actor where film_id =(
 select film_id from film where title='Gone with the wind' ));

 -- Determine the total number of rentals for each category of movies. 
select count(rental_id),fc.category_id from rental r 
inner join inventory i on r.inventory_id =i.inventory_id 
inner join film_category fc on fc.film_id=i.film_id
Group by fc.category_id;

 
 
  -- Find the average rental rate of movies in each language.
  select avg(f.rental_rate) ,name from film f right join
  language on f.language_id=language.language_id group by name ;
-- or
  select avg(rental_rate) ,(select name from language where language_id=film.language_id) language_name from film Group by language_id;
  
  -- Retrieve the customer names along with the total amount they've spent on rentals.
  select sum(p.amount), concat(c.first_name,' ',c.last_name) as name
  from payment p
  inner join customer c
  on c.customer_id=p.customer_id
  group by p.customer_id;
  
  -- or
  select sum(amount) ,(select concat(first_name ,' ',last_name) as name from customer where customer_id=payment.customer_id) as name from payment group by customer_id;
  
  -- List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
   select c.first_name,c.last_name, f.title from rental r 
 inner join customer c on r.customer_id=c.customer_id
 inner join inventory i on r.inventory_id=i.inventory_id
 inner join film f on i.film_id=f.film_id where c.customer_id in(
  select customer_id  from customer where address_id in(
  select address_id from address  where city_id in (
  select city_id from city where city='London')));
  
  -- Display the top 5 rented movies along with the number of times they've been rented. 
  select count(*) , f.title  from film f 
  inner join inventory i on f.film_id=i.film_id
  inner join rental r on r.inventory_id=i.inventory_id group by i.film_id
  order by count(*) desc Limit 5;
  
  -- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
  select first_name,last_name,customer_id from customer where customer_id in(
  select distinct(st_one.customer_id) from 
  (select  distinct(customer_id)  from  rental r
  inner join inventory i on i.inventory_id=r.inventory_id where i.store_id=1 order by customer_id ) as st_one
  inner join
  (select distinct(customer_id)  from  rental r
  inner join inventory i on i.inventory_id=r.inventory_id where i.store_id=2 order by customer_id) as st_two
  on
  st_one.customer_id=st_two.customer_id);
  
  
  